// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7SYQ0ljKfC1ATq_AZD9vc1IUeYIp4_k',
    appId: '1:417601558477:web:ecdb20275d82ff01229684',
    messagingSenderId: '417601558477',
    projectId: 'guardian-45ffd',
    authDomain: 'guardian-45ffd.firebaseapp.com',
    storageBucket: 'guardian-45ffd.firebasestorage.app',
    measurementId: 'G-QEXLHV0BCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJtu9UJOfVJIT5viwh4z1o9cFfe0oYJE',
    appId: '1:417601558477:android:9742afc37fffb955229684',
    messagingSenderId: '417601558477',
    projectId: 'guardian-45ffd',
    storageBucket: 'guardian-45ffd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lb6JGAd0WwoaGJ1H4PaMGsH5UjJafr8',
    appId: '1:417601558477:ios:96f2f0a3420187aa229684',
    messagingSenderId: '417601558477',
    projectId: 'guardian-45ffd',
    storageBucket: 'guardian-45ffd.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5lb6JGAd0WwoaGJ1H4PaMGsH5UjJafr8',
    appId: '1:417601558477:ios:96f2f0a3420187aa229684',
    messagingSenderId: '417601558477',
    projectId: 'guardian-45ffd',
    storageBucket: 'guardian-45ffd.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO7SYQ0ljKfC1ATq_AZD9vc1IUeYIp4_k',
    appId: '1:417601558477:web:d6c6c1b76881571d229684',
    messagingSenderId: '417601558477',
    projectId: 'guardian-45ffd',
    authDomain: 'guardian-45ffd.firebaseapp.com',
    storageBucket: 'guardian-45ffd.firebasestorage.app',
    measurementId: 'G-ZCJY7YD0NT',
  );
}
